### ISSUE TITLE
External Auth Error - Configuration problem with Nextcloud provider

### ISSUE THREAD

**Issue by shiipou** [codifyglobal/peertube-plugin-auth-oauth2#1]
Hi, i can't find how to configure correctly my Oauth2 Provider using this plugin.

Can you help me ?

![image](https://user-images.githubusercontent.com/38187238/99683681-e6b90e00-2a80-11eb-842f-ccc1347b747b.png)

My current configuration was this :

![image](https://user-images.githubusercontent.com/38187238/99684851-33511900-2a82-11eb-807c-bdbbe85239a7.png)

My current provider was my own Nextcloud instance with this client configured : 

![image](https://user-images.githubusercontent.com/38187238/99684024-43b4c400-2a81-11eb-8ac0-7fd44267aa2e.png)

PS: The token has been reset.

Can you help me to configure it ? I think my problem is in the `Identity access token URL parameter name`
Thank you for all.

EDIT: 
Here somes logs : 

```
info[11/19/2020, 4:10:22 PM] 82.64.0.0 - - [19/Nov/2020:15:10:22 +0000] "GET /plugins/auth-oauth2/1.0.1/auth/oauth2 HTTP/1.1" 302 678 "https://tube.nocturlab.fr/login" "Firefox"

error[11/19/2020, 4:10:26 PM] Access token error.

{
  "err": {
    "stack": "TypeError: Cannot read property 'body' of null\n    at new Request (/data/plugins/node_modules/servie/dist/node.js:148:30)\n    at Object.fetch (/data/plugins/node_modules/popsicle/dist/common.js:14:15)\n    at store.client.code.getToken.then (/data/plugins/node_modules/peertube-plugin-auth-oauth2/main.js:89:18)\n    at process._tickCallback (internal/process/next_tick.js:68:7)",
    "message": "Cannot read property 'body' of null"
  }
}

info[11/19/2020, 4:10:26 PM] 82.64.0.0 - - [19/Nov/2020:15:10:26 +0000] "GET /plugins/auth-oauth2/router/callback?state=1030d98510f08b6e316ac998f87e5124&code=YxZTOvt2[*****]4pFts HTTP/1.1" 302 102 "-" "Firefox"

info[11/19/2020, 4:10:26 PM] 82.64.0.0 - - [19/Nov/2020:15:10:26 +0000] "GET /login?externalAuthError=true HTTP/1.1" 304 - "-" "Firefox"

info[11/19/2020, 4:10:26 PM] 82.64.0.0 - - [19/Nov/2020:15:10:26 +0000] "GET /api/v1/config/ HTTP/1.1" 304 - "https://tube.nocturlab.fr/login?externalAuthError=true" "Firefox"

info[11/19/2020, 4:10:26 PM] 82.64.0.0 - - [19/Nov/2020:15:10:26 +0000] "GET /api/v1/oauth-clients/local HTTP/1.1" 304 - "https://tube.nocturlab.fr/login?externalAuthError=true" "Firefox"

info[11/19/2020, 4:10:26 PM] 82.64.0.0 - - [19/Nov/2020:15:10:26 +0000] "GET /api/v1/videos/languages HTTP/1.1" 304 - "https://tube.nocturlab.fr/login?externalAuthError=true" "Firefox" 
```

**Comment by moderniz** [comment]
Apologies for the late response.  I did not have notifications enabled.  Try selecting the checkbox near "Send identity token sent via HTTP header?"

NextCloud requires the authorization token in the header.  Please let me know if this does not resolve the issue.

**Comment by shiipou** [comment]
The same with the checkbox enabled :

![Capture d’écran 2021-01-04 à 10 59 27](https://user-images.githubusercontent.com/38187238/103523284-ed0e1880-4e7b-11eb-87dc-aefb421f60ab.png)

Can it be because of the "Identity access token URL parameter name" need to be at a specific value ? I use "code" as value but I didn't know if it the right one.
As I understand it change dynamicaly with the parameter I choose, but tell me if I'm wrong.

EDIT:
I have now a different error : 

```
error[04/01/2021 à 11:09:54] Auth method oauth2 of plugin peertube-plugin-auth-oauth2 did not provide a valid username.

info[04/01/2021 à 11:09:54] 90.24.0.0 - - [04/Jan/2021:10:09:54 +0000] "GET /plugins/auth-oauth2/router/callback?state=1030d98510f08b6e316ac998f87e5124&code=tVEp*****5kZ HTTP/1.1" 302 102 "-" "Firefox"

info[04/01/2021 à 11:09:54] 90.24.0.0 - - [04/Jan/2021:10:09:54 +0000] "GET /login?externalAuthError=true HTTP/1.1" 200 4139 "-" "Firefox"
```

I can be because of the Username of my account on the OAuth2 provider already exist on the Peertube instance, is it possible to link my existing account to the Oauth2 provider ?

**Comment by realkinetix** [comment]
I'm having very similar issues authenticating against a Pleroma instance.  I'm finding it very difficult to get enough information to figure out whether I've got things configured appropriately or not.  I've definitely tried a whackload of combinations of the Identity username field, Send identity token sent via HTTP header? and Identity access token URL parameter name fields, all to no avail, yet.

**Comment by realkinetix** [comment]
In fact, I'd love to know how you even figured out to use /plugins/auth-oauth2/router/callback as the redirection URL for nextcloud, as I couldn't find that detail anywhere until I tripped across this issue.

**Comment by normen** [comment]
Anyone got any further with this? I noticed this in the logs:

`[31merror[39m: Auth method oauth2 of plugin peertube-plugin-auth-oauth2 did not provide a valid username.`

**Comment by normen** [comment]
According to this file theres `id` and `display-name` provided by nextcloud, none of them seem to work..

https://github.com/markbates/goth/blob/master/providers/nextcloud/nextcloud.go

**Comment by moderniz** [comment]
OAuth defines two client types based on their ability to maintain the confidentiality of their client credentials. The two client types are `confidential` and `public`. 

A web application running on a server is an example of a `confidential` client.  A native mobile application is an example of a `public` client because a native application is installed and executed on the resource owner's device.

For a detailed explanation of these client types, see [RFC6749: 2.1. Client Types](https://tools.ietf.org/html/rfc6749#section-2.1).

To properly use this plugin, the OAuth 2.0 provider must support `confidential` clients.  [Nextcloud's](https://docs.nextcloud.com/server/20/admin_manual//configuration_server/oauth2.html) OAuth2 implementation does not support `confidential` clients.

**Comment by moderniz** [comment]
The readme now has information about the redirection endpoint: /plugins/auth-oauth2/router/callback

**Comment by moderniz** [comment]
This plugin does not support NextCloud's OAuth implementation.  I currently do not have plans to add support for NextCloud.   However, I encourage others to create a NextCloud implementation of this plugin.

**Comment by rasos** [comment]
I have seen the same error with keycloak as an IDM.

After checking `Send identity token sent via HTTP header?` and adding `code` as identity access token URL parameter, it worked. 

Thank you for this very useful plugin.

**Comment by shiipou** [comment]
> I have seen the same error with keycloak as an IDM.
> 
> After checking `Send identity token sent via HTTP header?` and adding `code` as identity access token URL parameter, it worked.
> 
> Thank you for this very useful plugin.

Thanks for letting me know.
But that didn't work with Nextcloud.

**Comment by normen** [comment]
> This plugin does not support NextCloud's OAuth implementation. I currently do not have plans to add support for NextCloud. However, I encourage others to create a NextCloud implementation of this plugin.

This sounds like you at least have an idea about what would need to be changed?
